### ISSUE TITLE
Idea / Suggestion

### ISSUE THREAD

**Issue by E1sterrier** [hitsub/CookieAssistant#47] opened 2021-09-21 05:03 UTC
Idea / Suggestion

1. For 1000 reincarnations, it would be nice if there was a function to ascend and reincarnate as soon as HC is accumulated.

2. It would be nice if "AutoSwitch season" allows you to choose to lock to any season after getting all the upgrades.

3. For "AutoSpellCast" it would be nice to have the ability to hit "Gambler's Fever Dreams" repeatedly in order to gain chant count.

4. It would be great if the "Stock Market" and "Garden" could be automated.

**Comment by hitsub** [comment] 2021-09-23 10:18
@E1sterrier  Thanks for suggentions.

1. Duplicate of #17 
2. I made an issue #48
3. I think no point in chanting anything other than "Hand of Fate",  but what's the benefit of random chanting?
4. Automatic Garden is duplicate of #16 .
Automatic Stock will not implement.  See #23 .

**Comment by hitsub** [comment] 2021-09-23 10:29
Since I don't feel the need for this feature, I will close this Issue.
If you would like to write an explanation for me, please re-open this issue.

**Closed by hitsub** 2021-09-23 10:29 UTC
